include:
  - proxy.yaml

services:
  db:
    image: mysql:8
    command: --mysql-native-password=ON
    restart: on-failure
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${MYSQL_DATABASE}
      - MYSQL_USER: ${MYSQL_USER}
      - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    volumes:
      - ./docker_volumes/mysql:/var/lib/mysql:delegated
    ports:
      - 3306:3306
    networks:
      backend:
        ipv4_address: 172.20.0.10

  web:
    image: my-python-app
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      backend:
        ipv4_address: 172.20.0.5

networks:
  backend:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/24

