include:
  - proxy.yaml

services:
  db:
    image: mysql:8
    command: --mysql-native-password=ON
    restart: on-failure
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test_db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    volumes:
      - ./docker_volumes/mysql:/var/lib/mysql:delegated
    ports:
      - 3306:3306
    networks:
      backend:
        ipv4_address: 172.20.0.10

  web:
    image: my-python-app
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_USER=test_db
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=test_db
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      backend:
        ipv4_address: 172.20.0.5

networks:
  backend:
    external: true
