version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: my-python-app
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    ports:
      - "8090:80"

  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

networks:
  backend:
    driver: bridge

x-include:
  - proxy.yaml
