# Используем базовый образ python 3.9
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем содержимое текущей директории в рабочую директорию контейнера
COPY . .

# Устанавливаем зависимости из requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Определяем команду по умолчанию
CMD ["python", "main.py"]
